export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const BEGIN_PRODUCTS_DOWNLOAD = 'BEGIN_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'PRODUCTS_DOWNLOAD_SUCCESS';
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const DELETED_PRODUCT_SUCCESS = 'DELETED_PRODUCT_SUCCESS';
export const DELETED_PRODUCT_ERROR = 'DELETED_PRODUCT_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const BEGIN_PRODUCT_EDITION = 'BEGIN_PRODUCT_EDITION';
export const EDITED_PRODUCT_SUCCESS = 'EDITED_PRODUCT_SUCCESS';
export const EDITED_PRODUCT_ERROR = 'EDITED_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';